// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkY6YslV425bvPtf4LJLM0lvOFVKtOYVg',
    appId: '1:17918511092:web:28b13e804697767d7a9ba1',
    messagingSenderId: '17918511092',
    projectId: 'knowledgekubeauth',
    authDomain: 'knowledgekubeauth.firebaseapp.com',
    storageBucket: 'knowledgekubeauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFBgCt1It0UqnBwwRvkXYHfV6nTTmjCs',
    appId: '1:17918511092:android:7b840184d44ab0557a9ba1',
    messagingSenderId: '17918511092',
    projectId: 'knowledgekubeauth',
    storageBucket: 'knowledgekubeauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa7rVHGT-P_xg1-TeReemQKqk9WQE0gFI',
    appId: '1:17918511092:ios:5e066301506def837a9ba1',
    messagingSenderId: '17918511092',
    projectId: 'knowledgekubeauth',
    storageBucket: 'knowledgekubeauth.appspot.com',
    iosBundleId: 'com.example.knowledgeKube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa7rVHGT-P_xg1-TeReemQKqk9WQE0gFI',
    appId: '1:17918511092:ios:29e95e4e0211b32c7a9ba1',
    messagingSenderId: '17918511092',
    projectId: 'knowledgekubeauth',
    storageBucket: 'knowledgekubeauth.appspot.com',
    iosBundleId: 'com.example.knowledgeKube.RunnerTests',
  );
}
